[theme]
base="dark"
primaryColor="#8B0000"             # Customize primary color (buttons, sliders)
backgroundColor="#0E1117"         # Main background
secondaryBackgroundColor="#262730" # Sidebar and widget backgrounds
textColor="#FAFAFA"               # Text color
font="sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
